### ISSUE TITLE
merge with containers/build ?

### ISSUE THREAD

**Issue by vbatts** [cyphar/oboci#1]
https://github.com/containers/build
formerly the build tool for only appc images, is being rebranded and wants to add output to OCI images.

Would this be something you're willing to consider merging with?

**Comment by cyphar** [comment]
If they're willing to use `umoci` -- sure. To be honest this project will basically just become a shell script (but written in Go) soon since `umoci` has effectively everything you need.

**Comment by vbatts** [comment]
right on.
